# Copyright 2019 The CDAP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Base.Name}}
  namespace: {{.Base.Namespace}}
  {{if .Base.Labels}}
  labels:
    {{range $k,$v := .Base.Labels}}
    {{$k}}: "{{$v}}"
    {{end}}
  {{end}}
spec:
  selector:
    matchLabels:
      {{range $k,$v := .Base.Labels}}
      {{$k}}: "{{$v}}"
      {{end}}
  replicas: {{.Base.Replicas}}
  template:
    metadata:
      labels:
        {{range $k,$v := .Base.Labels }}
        {{$k}}: "{{$v}}"
        {{end}}
    spec:
      {{if .Base.ServiceAccountName}}
      serviceAccountName: {{.Base.ServiceAccountName}}
      {{end}}
      nodeSelector:
        {{range $k,$v := .Base.NodeSelector}}
        {{$k}}: "{{$v}}"
        {{end}}
      {{if .Base.RuntimeClassName}}
      runtimeClassName: {{.Base.RuntimeClassName}}
      {{end}}
      {{if .Base.PriorityClassName}}
      priorityClassName: {{.Base.PriorityClassName}}
      {{end}}
      terminationGracePeriodSeconds: 120
      containers:
        {{range $c := .Containers}}
        - name: {{$c.Name}}
          image: {{$c.Image}}
          workingDir: {{$c.WorkingDir}}
          command:
          {{range $v := $c.Command }}
            - {{$v}}
          {{end}}
          args:
          {{range $v := $c.Args }}
            - {{$v}}
          {{end}}
          {{if $c.ImagePullPolicy}}
          imagePullPolicy: {{$c.ImagePullPolicy}}
          {{end}}
          env:
          {{range $e := $c.Env }}
          - name: "{{$e.Name}}"
            {{if $e.Value}}
            value: "{{$e.Value}}"  
            {{end}}
            {{if $e.ValueFrom}}
            valueFrom:
              {{if $e.ValueFrom.SecretKeyRef}}
              secretKeyRef:
                name: {{$e.ValueFrom.SecretKeyRef.LocalObjectReference.Name}}
                key: {{$e.ValueFrom.SecretKeyRef.Key}}
              {{end}}
            {{end}}
          {{end}}
          resources:
            {{if $c.ResourceRequests}}
            requests:
              {{range $k, $v := $c.ResourceRequests}}
              {{$k}}: {{$v.String}}
              {{end}}
            {{end}}
            {{if $c.ResourceLimits}}
            limits:
              {{range $k, $v := $c.ResourceLimits}}
              {{$k}}: {{$v.String}}
              {{end}}
            {{end}}

          {{if $c.LivenessProbe}}
          livenessProbe:
            {{if $c.LivenessProbe.InitialDelaySeconds }}
            initialDelaySeconds: {{$c.LivenessProbe.InitialDelaySeconds }}
            {{end}}
            {{if $c.LivenessProbe.TimeoutSeconds }}
            timeoutSeconds: {{$c.LivenessProbe.TimeoutSeconds }}
            {{end}}
            {{if $c.LivenessProbe.PeriodSeconds }}
            periodSeconds: {{$c.LivenessProbe.PeriodSeconds }}
            {{end}}
            {{if $c.LivenessProbe.SuccessThreshold }}
            successThreshold: {{$c.LivenessProbe.SuccessThreshold }}
            {{end}}
            {{if $c.LivenessProbe.FailureThreshold }}
            failureThreshold: {{$c.LivenessProbe.FailureThreshold }}
            {{end}}
            
            {{if $c.LivenessProbe.Handler}}

            {{if $c.LivenessProbe.Handler.HTTPGet}}
            httpGet:
              {{if $c.LivenessProbe.Handler.HTTPGet.Path}}
              path: {{$c.LivenessProbe.Handler.HTTPGet.Path}} 
              {{end}}
              port: {{$c.LivenessProbe.Handler.HTTPGet.Port}}
              {{if $c.LivenessProbe.Handler.HTTPGet.Scheme}}
              scheme: {{$c.LivenessProbe.Handler.HTTPGet.Scheme}}
              {{end}}
              {{if $c.LivenessProbe.Handler.HTTPGet.Host}}
              host: {{$c.LivenessProbe.Handler.HTTPGet.Host}}
              {{end}}
              {{if $c.LivenessProbe.Handler.HTTPGet.HTTPHeaders}}
              httpHeaders:
                {{range $h := $c.LivenessProbe.Handler.HTTPGet.HTTPHeaders }}
              - name: {{$h.Name}}
                value: {{$h.Value}}
                {{end}}
              {{end}}
            {{end}}

            {{if $c.LivenessProbe.Handler.Exec}}
            exec:
              command:
              {{range $v := $c.LivenessProbe.Handler.Exec.Command }}
              - {{$v}}
              {{end}}
            {{end}}

            {{if $c.LivenessProbe.Handler.TCPSocket}}
            tcpSocket:
              port: {{$c.LivenessProbe.Handler.TCPSocket.Port}}
            {{end}}

            {{end}}

          {{end}}

          {{if $c.ReadinessProbe}}
          readinessProbe:
            {{if $c.ReadinessProbe.InitialDelaySeconds }}
            initialDelaySeconds: {{$c.ReadinessProbe.InitialDelaySeconds }}
            {{end}}
            {{if $c.ReadinessProbe.TimeoutSeconds }}
            timeoutSeconds: {{$c.ReadinessProbe.TimeoutSeconds }}
            {{end}}
            {{if $c.ReadinessProbe.PeriodSeconds }}
            periodSeconds: {{$c.ReadinessProbe.PeriodSeconds }}
            {{end}}
            {{if $c.ReadinessProbe.SuccessThreshold }}
            successThreshold: {{$c.ReadinessProbe.SuccessThreshold }}
            {{end}}
            {{if $c.ReadinessProbe.FailureThreshold }}
            failureThreshold: {{$c.ReadinessProbe.FailureThreshold }}
            {{end}}
            {{if $c.ReadinessProbe.Handler}}

            {{if $c.ReadinessProbe.Handler.HTTPGet}}
            httpGet:
              {{if $c.ReadinessProbe.Handler.HTTPGet.Path}}
              path: {{$c.ReadinessProbe.Handler.HTTPGet.Path}} 
              {{end}}
              port: {{$c.ReadinessProbe.Handler.HTTPGet.Port}}
              {{if $c.ReadinessProbe.Handler.HTTPGet.Scheme}}
              scheme: {{$c.ReadinessProbe.Handler.HTTPGet.Scheme}}
              {{end}}
              {{if $c.ReadinessProbe.Handler.HTTPGet.Host}}
              host: {{$c.ReadinessProbe.Handler.HTTPGet.Host}}
              {{end}}
              {{if $c.ReadinessProbe.Handler.HTTPGet.HTTPHeaders}}
              httpHeaders:
                {{range $h := $c.ReadinessProbe.Handler.HTTPGet.HTTPHeaders }}
              - name: {{$h.Name}}
                value: {{$h.Value}}
                {{end}}
              {{end}}
            {{end}}
            
            {{if $c.ReadinessProbe.Handler.Exec}}
            exec:
              command:
              {{range $v := $c.ReadinessProbe.Handler.Exec.Command }}
              - {{$v}}
              {{end}}
            {{end}}

            {{if $c.ReadinessProbe.Handler.TCPSocket}}
            tcpSocket:
              port: {{$c.ReadinessProbe.Handler.TCPSocket.Port}}
            {{end}}

            {{end}}

          {{end}}

          {{if $c.Ports}}
          ports:
            {{range $cp := $c.Ports}}
          - containerPort: {{$cp.ContainerPort}}
            {{if $cp.Name}}
            name: {{$cp.Name}}
            {{end}}
            {{if $cp.Protocol}}
            protocol: {{$cp.Protocol}}
            {{end}}
            {{if $cp.HostPort}}
            hostPort: {{$cp.HostPort}}
            {{end}}
            {{if $cp.HostIP}}
            hostIP: {{$cp.HostIP}}
            {{end}}
            {{end}}
          {{end}}
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
            - name: cdap-conf
              mountPath: /etc/cdap/conf
              readOnly: true
            - name: hadoop-conf
              mountPath: /etc/hadoop/conf
              readOnly: true
            - name: cdap-sysappconf
              mountPath: /opt/cdap/master/system-app-config
              readOnly: true
            {{if $.Base.SecuritySecret}}
            - name: cdap-security
              mountPath: /etc/cdap/security
              readOnly: true
            {{end}}
            {{range $k,$v := $.Base.ConfigMapVolumes}}
            - name: cdap-cm-vol-{{$k}}
              mountPath: {{$v}}
            {{end}}
            {{range $k,$v := $.Base.SecretVolumes}}
            - name: cdap-se-vol-{{$k}}
              mountPath: {{$v}}
            {{end}}
          
            {{if $c.VolumeMounts}}
            {{range $vm := $c.VolumeMounts}}
            - name: {{$vm.Name}}
              mountPath: {{$vm.MountPath}}
              {{if $vm.ReadOnly }}
              readOnly: {{$vm.ReadOnly}}
              {{end}}
            {{end}}
            {{end}}

      {{end}}
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "pod.labels.properties"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "pod.name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "pod.uid"
                fieldRef:
                  fieldPath: metadata.uid
        - name: cdap-conf
          configMap:
            name: {{.Base.CConf}}
        - name: hadoop-conf
          configMap:
            name: {{.Base.HConf}}
        - name: cdap-sysappconf
          configMap:
            name: {{.Base.SysAppConf}}
        {{if .Base.SecuritySecret}}
        - name: cdap-security
          secret:
            secretName: {{.Base.SecuritySecret}}
        {{end}}
        {{range $k,$v := $.Base.ConfigMapVolumes}}
        - name: cdap-cm-vol-{{$k}}
          configMap:
            name: {{$k}}
        {{end}}
        {{range $k,$v := $.Base.SecretVolumes}}
        - name: cdap-se-vol-{{$k}}
          secret:
            secretName: {{$k}}
        {{end}}
