name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Kubebuilder
      run: |
        version=2.3.1
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_${os}_${arch}.tar.gz"
        tar -zxvf kubebuilder_${version}_${os}_${arch}.tar.gz
        sudo mv kubebuilder_${version}_${os}_${arch} /usr/local/kubebuilder
        rm -f kubebuilder_${version}_${os}_${arch}.tar.gz
        sudo find /usr/local/kubebuilder/bin -type f -exec ln -s {} /usr/local/bin \;
    - name: Test
      run: make manifests test
