name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Kubebuilder
      run: |
        version=3.2.0
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${os}_${arch}"
        sudo chmod +x kubebuilder
        sudo mv kubebuilder /usr/local/bin/
    - name: Test
      run: make manifests test
